dist: trusty
sudo: false
language: node_js
node_js:
  - '11.0'
before_script:
  - npm install -g @angular/cli
script:
  - npm install
  - npm run-script build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAW5B3DWY7XATC7I35
  secret_access_key: $SECRET_ACCESS_KEY
  bucket: audit-tool-frontend
  local-dir: dist/angular-boiler-plate
  upload-dir: ap-south-1
  acl: public_read
  on:
    repo: WPOCanvas/Audit-Tool-Frontend
    branches:
      only:
        - master
