dist: trusty
sudo: false
language: node_js
node_js:
- '11.0'
before_script:
- npm install -g @angular/cli
script:
- npm install
- npm run-script build
deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAW5B3DWY7ZCFBEG4T
  secret_access_key:
    secure: RCjGcrp0OmLnXYTNCFnpH0FmQxQLL+xDqNTry7VVJa3+o6emhfyHTVG72mlY44y5iLRuI8ZFTBiylAEdc+D2BmdFf7zjDf3Z7gZ/LzO0ZKpPs/3L3rRxelzT+YKUEjovPFvM2DNdTGRPu+ZwR8VAvxYTtwfTWHmQCNuYnL3nNS8YSMGV9IGvwJB9u8ngmR8y18VRvi2sYJOkEKMapQ4YBKFRzmBFT8o8QJ7rBgIU6ISRf9yD2ZxsOVUEkFdJDoGX7g2jWPbtBt2U7LvbQhRrKv/E9wSSbnz2cXcXeN1/Ro+tMSDVp84vK0+mtl+wXA1YPI78IDuJqINv0w/je7las1hXPr6n83ghJUVwwmTEuPSxnht9/uwESmxlHWJRdQO28i3r8zZig2ujqonFGJDKrVnJGNSJou0cYnbwgQwNbOYnxv2vm08JH7tolDJDIlJh17s/IEvZMlZz80AfQnEtMWQKmy2LkzEwYqA9oWCH4zfL0frAjUwJzL1llegTvhQUOGYJQoVnNZNn3IUDuqbz7yL2R3cpdw6yCLyklLIQmP49ILO34tpz5HcCXnZQxwd1Ou8ZrrLAynLJd8Z8tmg1mij9Un+d9LTZUJvON99v2O2TizW5tgaH17zCNQHni8yrKB2K4TDQts/CWRl09ww80ZhFUTYh9tgXvwrWCTxahls=
  bucket: audit-tool-frontend
  local-dir: dist/angular-boiler-plate
  upload-dir: ap-south-1
  acl: public_read
  on:
    repo: WPOCanvas/Audit-Tool-Frontend
    branches:
      only:
      - master