dist: trusty
sudo: false

language: node_js
node_js:
  - '11.0'

before_script:
  - npm install -g @angular/cli
  
script:
  - npm install
  - npm run-script build

deploy:
  provider: s3
  skip_cleanup: true
  access_key_id: AKIAW5B3DWY7XATC7I35
  secret_access_key:
    secure: WMMNvA/dxROQsi3OkUTy1LUCUQI4qoBJjTVTqkYUPpWCeS7vocRrKfuJ9Noy3X/ZGMgvCihQ1tAEzYMOHBSutfPpBJEomP6jHHNucziRMvHg9wDTWIcggyYmI5leXP5wlp0Hb199RuRdIkxUqaPGlpu2p7wGm+LB3tTpmV+nWncSC89dFRloeiz657m8ZKU7g4RYr7srNKTeZeaO8/JSBW0KPo4GkfI0CtxwcNHmmM2hPi87m+4S++NDIAD3WaJZzN5Nj8zH4dpdv8A6Enuxuc7CbUEjFPuDqrLrRxuF+36sdqKU7moFljcmr6d6XjDL77AI0LPMPVh3EPI0jXpLeZwPKSM4MlOjkSYEpy3ZAHHfhE2LBp3UXsnsW0mZDmvj4n5MNl/jE2u8mW/pXfepSNxxYT63MJ5e+QMunB9yHDlVJdH4HI6ux4viNey+OytsvtHOlwN1xq/TPVM4vb5S66nF6d6IY3ip/toihLtcqOKeU7GjULKS7UZkju/ZZqNf9oaqsxctq5jIGiHI/2J192nuhcbW2jNHwPHiFjfIiXsPGWGFw03H1dl4E3le6waXzWMcS36jv+WISLS6sdMQ+JD3+UQdgf+Beu6l/LdeD/Ek/5cptO1VCXs/z6Ju4gqCG4cIFj0TeUlEACPM5RTCFjO+/9qGbyXIkla5Wa7qPsU=
  bucket: audit-tool-frontend
  local-dir: dist/angular-boiler-plate
  upload-dir: ap-south-1
  acl: public_read
  on:
    repo: WPOCanvas/Audit-Tool-Frontend
    branches: 
      only:
        - master
